#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATASETS="${DATASETS:-DBE,NIPS,XES}" \
RUNS="${RUNS:-1}" \
MODES="${MODES:-all}" \
MODEL="${MODEL:-gpt-5.2}" \
WINDOW="${WINDOW:-5}" \
PEER_TOP_PER_LABEL="${PEER_TOP_PER_LABEL:-2}" \
SELF_TOPK="${SELF_TOPK:-3}" \
SELF_COUNTER="${SELF_COUNTER:-1}" \
SERVICE_TIER="${SERVICE_TIER:-flex}" \
API_KEY_ENV="${API_KEY_ENV:-OPENAI_API_KEY}" \
API_BASE_URL="${API_BASE_URL:-}" \
EVIDENCE_WORKERS="${EVIDENCE_WORKERS:-4}" \
MAX_WORKERS="${MAX_WORKERS:-8}" \
SAVE_EVERY="${SAVE_EVERY:-25}" \
INVALID_RETRIES="${INVALID_RETRIES:-3}" \
RETRIEVE_ONLY="${RETRIEVE_ONLY:-0}" \
python3 "${SCRIPT_DIR}/run_steer_kt.py"
